version: '3.3'

services:

  #############################################################
  ######################### SERVICE ###########################
  #############################################################

  eureka-service:
    image: 'borelanjo/eureka-service:latest'
    networks:
      - borelanjo-network
    ports:
      - "8761:8761"

  gateway-service:
    image: 'borelanjo/gateway-service:latest'
    networks:
      - borelanjo-network
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
    environment:
      EUREKA_URL: gateway-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'

  customer-service:
    image: 'borelanjo/customer-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      EUREKA_URL: customer-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'

  comprador-service:
    image: 'borelanjo/customer-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      EUREKA_URL: comprador-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'

  product-service:
    image: 'borelanjo/product-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      EUREKA_URL: product-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'

  seller-service:
    image: 'borelanjo/seller-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      EUREKA_URL: seller-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'

  store-service:
    image: 'borelanjo/store-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      EUREKA_URL: store-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'

  supplier-service:
    image: 'borelanjo/supplier-service:latest'
    networks:
      - borelanjo-network
    depends_on:
      - eureka-service
    environment:
      EUREKA_URL: supplier-service
      EUREKA_DEFAULT_ZONE: 'http://eureka-service:8761/eureka'

#############################################################
######################### NETWORK ###########################
#############################################################
networks:
  borelanjo-network:
    driver: "bridge"