eureka:
  instance:
    hostname: ${EUREKA_URL:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customers
          uri: lb://CUSTOMERS
          predicates:
            - Path=/customers/**
        - id: products
          uri: lb://PRODUCTS
          predicates:
            - Path=/products/**
        - id: sellers
          uri: lb://sellers
          predicates:
            - Path=/sellers/**
        - id: stores
          uri: lb://stores
          predicates:
            - Path=/stores/**
        - id: suppliers
          uri: lb://suppliers
          predicates:
            - Path=/suppliers/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
